# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7a78f545bfe42c93f85d25bc28bee2b21638ab68fb00e9cc87e6aaeaddf18e57eb57a5412cc2ed6a2e15059aa79f24cf366d88406b082f8cc2f9703cba470fe

test:
  secret_key_base: b7ef9a3c615c7ce6d77a09352da02348da0794d1b03cc10cbc8ed7e1927cb53b6ae1f7ff979da6e4ac33abf667c58a33dd7becb647bb10d35da5371b9c816db7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
