# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11b5aa3969aed1768f0a69c1059eff77cfcfada75bf0cefb5a1bb44b26dd084747d33fd4206555e206bef345409f2a2eefec280450ce560f75f6691b1e204248

test:
  secret_key_base: fd185b3f1ac7c6b681b1828ccf36c68d345f84742ffbcbe9c71372c4e943fe5cf698554de74e684c50cf6b743579ee097c9713c0ad6b22598f908490bd8b63cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
